### ISSUE TITLE
Reply-to address for each location

### ISSUE THREAD

**Issue by vallu** [jweisman/alma-scheduler#13]
Hello,

Our suggestion is that it would be possible to configure a Reply-to email address for each location, so that each location can receive directly the feedback from users: cancellations o modifications to the scheduled appointments. 

With only one Reply-to email address for the whole institution we need to resend the messages to the affected locations.

Thank you very much.

**Comment by jweisman** [comment]
Hi @vallu . We added a reply to address at the library level. Hope this is helpful to you.
